#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <QGraphicsScene>

#include "../libGP/tiffimg.h"
#include "tiffgraphicsview.h"

namespace Ui {
  class MainWindow;
}

class MainWindow : public QMainWindow
{
  Q_OBJECT

public:
  explicit MainWindow(QWidget *parent = 0);
  ~MainWindow();
  TiffImg * mTifImg;
  void setGraphicsScene(QGraphicsScene * scene);
  void setTifImage();
  void updateImage();
public slots:
  ///
  /// \brief setBrightness Set the brightness of the image.
  /// \param brightness Brightness as int value, typically between 0 and 32000
  ///
  void setBrightness(int brightness);
  ///
  /// \brief setContrast Set the contrast of the image.
  /// \param contrast Contrast as int value between 0 and 100.
  ///
  void setContrast(int contrast);
  ///
  /// \brief setRGOperator Set the operator for calculations on images.
  /// \param op String with operator, typicalle a single char.
  ///
  void setRGOperator(const QString& op);
  ///
  /// \brief exchangeRG Exchange the order of values for calculations on images.
  ///
  void exchangeRG();
  ///
  /// \brief selectImage Select the Image to show.
  ///
  void selectImage();
  ///
  /// \brief loadImage Load a multi Tiff Image generated by GenePix.
  ///
  void loadImage();
  ///
  /// \brief loadGal Load GenePix array list.
  ///
  void loadGal();
  ///
  /// \brief loadGpr Load a GenPix result file (gpr).
  ///
  void loadGpr();

private:
  ///
  /// \brief ui The formular for the main window.
  ///
  Ui::MainWindow *ui;

  QGraphicsScene * mTiffScene;
  TiffGraphicsView * mTiffView;
  QGraphicsPixmapItem * mPixmapItem;

};




#endif // MAINWINDOW_H
